using './web.module.bicep'

param azure_storage_outputs_tableendpoint = '{{ .Env.AZURE_STORAGE_TABLEENDPOINT }}'
param certificateName = '{{ parameter "certificateName" }}'
param domainApex = '{{ parameter "domainApex" }}'
param domainWww = '{{ parameter "domainWww" }}'
param outputs_azure_container_apps_environment_default_domain = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param outputs_azure_container_apps_environment_id = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param outputs_azure_container_registry_endpoint = '{{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param outputs_azure_container_registry_managed_identity_id = '{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param web_containerimage = '{{ .Image }}'
param web_containerport = '{{ targetPortOrDefault 8080 }}'
param web_identity_outputs_clientid = '{{ .Env.WEB_IDENTITY_CLIENTID }}'
param web_identity_outputs_id = '{{ .Env.WEB_IDENTITY_ID }}'
param wwwCertificateName = '{{ parameter "wwwCertificateName" }}'
